apiVersion: apps/v1

kind: Deployment

metadata:
  name: my-backend-depl
  labels:
    app: my-backend
    type: backend

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-backend
        type: backend

    spec:
      containers:
       - name: my-backend-container
         image: mlabuda2/backend
         env:
          - name: PGUSER
            valueFrom:
                configMapKeyRef:
                    name: my-app-config
                    key: PGUSER
          - name: PGDATABASE
            valueFrom:
                configMapKeyRef:
                    name: my-app-config
                    key: PGDATABASE
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                    name: postgres-secret
                    key: PGPASSWORD
          - name: PGPORT
            valueFrom:
                configMapKeyRef:
                    name: my-app-config
                    key: PGPORT
  replicas: 3
  selector:
      matchLabels:
          app: my-backend
          type: backend
