version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mati
      - POSTGRES_PASSWORD=sztyczaczek
      - POSTGRES_DB=mati
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: