version: '3'

services:
    myredis:
        image: redis:latest
        command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    mywebapp:
        build: .
        ports:
            - "9090:8080"